# -*- coding: utf-8 -*-
# Copyright (c) 2022-2024 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seats.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="seats.proto",
    package="sdv.edge.comfort.seats.v1",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0bseats.proto\x12\x19sdv.edge.comfort.seats.v1"<\n\x0bMoveRequest\x12-\n\x04seat\x18\x01 \x01(\x0b\x32\x1f.sdv.edge.comfort.seats.v1.Seat"\x0b\n\tMoveReply"\x9c\x01\n\x14MoveComponentRequest\x12\x35\n\x04seat\x18\x01 \x01(\x0b\x32\'.sdv.edge.comfort.seats.v1.SeatLocation\x12;\n\tcomponent\x18\x02 \x01(\x0e\x32(.sdv.edge.comfort.seats.v1.SeatComponent\x12\x10\n\x08position\x18\x03 \x01(\x05"\x14\n\x12MoveComponentReply"4\n\x16\x43urrentPositionRequest\x12\x0b\n\x03row\x18\x01 \x01(\r\x12\r\n\x05index\x18\x02 \x01(\r"E\n\x14\x43urrentPositionReply\x12-\n\x04seat\x18\x01 \x01(\x0b\x32\x1f.sdv.edge.comfort.seats.v1.Seat"x\n\x04Seat\x12\x39\n\x08location\x18\x01 \x01(\x0b\x32\'.sdv.edge.comfort.seats.v1.SeatLocation\x12\x35\n\x08position\x18\x02 \x01(\x0b\x32#.sdv.edge.comfort.seats.v1.Position"*\n\x0cSeatLocation\x12\x0b\n\x03row\x18\x01 \x01(\r\x12\r\n\x05index\x18\x02 \x01(\r"g\n\x08Position\x12\x0c\n\x04\x62\x61se\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ushion\x18\x02 \x01(\x05\x12\x0e\n\x06lumbar\x18\x03 \x01(\x05\x12\x14\n\x0cside_bolster\x18\x04 \x01(\x05\x12\x16\n\x0ehead_restraint\x18\x05 \x01(\x05*X\n\rSeatComponent\x12\x08\n\x04\x42\x41SE\x10\x00\x12\x0b\n\x07\x43USHION\x10\x01\x12\n\n\x06LUMBAR\x10\x02\x12\x10\n\x0cSIDE_BOLSTER\x10\x03\x12\x12\n\x0eHEAD_RESTRAINT\x10\x04\x32\xc5\x02\n\x05Seats\x12T\n\x04Move\x12&.sdv.edge.comfort.seats.v1.MoveRequest\x1a$.sdv.edge.comfort.seats.v1.MoveReply\x12o\n\rMoveComponent\x12/.sdv.edge.comfort.seats.v1.MoveComponentRequest\x1a-.sdv.edge.comfort.seats.v1.MoveComponentReply\x12u\n\x0f\x43urrentPosition\x12\x31.sdv.edge.comfort.seats.v1.CurrentPositionRequest\x1a/.sdv.edge.comfort.seats.v1.CurrentPositionReplyb\x06proto3',
)

_SEATCOMPONENT = _descriptor.EnumDescriptor(
    name="SeatComponent",
    full_name="sdv.edge.comfort.seats.v1.SeatComponent",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="BASE",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="CUSHION",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="LUMBAR",
            index=2,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="SIDE_BOLSTER",
            index=3,
            number=3,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="HEAD_RESTRAINT",
            index=4,
            number=4,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=694,
    serialized_end=782,
)
_sym_db.RegisterEnumDescriptor(_SEATCOMPONENT)

SeatComponent = enum_type_wrapper.EnumTypeWrapper(_SEATCOMPONENT)
BASE = 0
CUSHION = 1
LUMBAR = 2
SIDE_BOLSTER = 3
HEAD_RESTRAINT = 4


_MOVEREQUEST = _descriptor.Descriptor(
    name="MoveRequest",
    full_name="sdv.edge.comfort.seats.v1.MoveRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="seat",
            full_name="sdv.edge.comfort.seats.v1.MoveRequest.seat",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=42,
    serialized_end=102,
)


_MOVEREPLY = _descriptor.Descriptor(
    name="MoveReply",
    full_name="sdv.edge.comfort.seats.v1.MoveReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=104,
    serialized_end=115,
)


_MOVECOMPONENTREQUEST = _descriptor.Descriptor(
    name="MoveComponentRequest",
    full_name="sdv.edge.comfort.seats.v1.MoveComponentRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="seat",
            full_name="sdv.edge.comfort.seats.v1.MoveComponentRequest.seat",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="component",
            full_name="sdv.edge.comfort.seats.v1.MoveComponentRequest.component",
            index=1,
            number=2,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="position",
            full_name="sdv.edge.comfort.seats.v1.MoveComponentRequest.position",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=118,
    serialized_end=274,
)


_MOVECOMPONENTREPLY = _descriptor.Descriptor(
    name="MoveComponentReply",
    full_name="sdv.edge.comfort.seats.v1.MoveComponentReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=276,
    serialized_end=296,
)


_CURRENTPOSITIONREQUEST = _descriptor.Descriptor(
    name="CurrentPositionRequest",
    full_name="sdv.edge.comfort.seats.v1.CurrentPositionRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="row",
            full_name="sdv.edge.comfort.seats.v1.CurrentPositionRequest.row",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="index",
            full_name="sdv.edge.comfort.seats.v1.CurrentPositionRequest.index",
            index=1,
            number=2,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=298,
    serialized_end=350,
)


_CURRENTPOSITIONREPLY = _descriptor.Descriptor(
    name="CurrentPositionReply",
    full_name="sdv.edge.comfort.seats.v1.CurrentPositionReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="seat",
            full_name="sdv.edge.comfort.seats.v1.CurrentPositionReply.seat",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=352,
    serialized_end=421,
)


_SEAT = _descriptor.Descriptor(
    name="Seat",
    full_name="sdv.edge.comfort.seats.v1.Seat",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="location",
            full_name="sdv.edge.comfort.seats.v1.Seat.location",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="position",
            full_name="sdv.edge.comfort.seats.v1.Seat.position",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=423,
    serialized_end=543,
)


_SEATLOCATION = _descriptor.Descriptor(
    name="SeatLocation",
    full_name="sdv.edge.comfort.seats.v1.SeatLocation",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="row",
            full_name="sdv.edge.comfort.seats.v1.SeatLocation.row",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="index",
            full_name="sdv.edge.comfort.seats.v1.SeatLocation.index",
            index=1,
            number=2,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=545,
    serialized_end=587,
)


_POSITION = _descriptor.Descriptor(
    name="Position",
    full_name="sdv.edge.comfort.seats.v1.Position",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="base",
            full_name="sdv.edge.comfort.seats.v1.Position.base",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="cushion",
            full_name="sdv.edge.comfort.seats.v1.Position.cushion",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="lumbar",
            full_name="sdv.edge.comfort.seats.v1.Position.lumbar",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="side_bolster",
            full_name="sdv.edge.comfort.seats.v1.Position.side_bolster",
            index=3,
            number=4,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="head_restraint",
            full_name="sdv.edge.comfort.seats.v1.Position.head_restraint",
            index=4,
            number=5,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=589,
    serialized_end=692,
)

_MOVEREQUEST.fields_by_name["seat"].message_type = _SEAT
_MOVECOMPONENTREQUEST.fields_by_name["seat"].message_type = _SEATLOCATION
_MOVECOMPONENTREQUEST.fields_by_name["component"].enum_type = _SEATCOMPONENT
_CURRENTPOSITIONREPLY.fields_by_name["seat"].message_type = _SEAT
_SEAT.fields_by_name["location"].message_type = _SEATLOCATION
_SEAT.fields_by_name["position"].message_type = _POSITION
DESCRIPTOR.message_types_by_name["MoveRequest"] = _MOVEREQUEST
DESCRIPTOR.message_types_by_name["MoveReply"] = _MOVEREPLY
DESCRIPTOR.message_types_by_name["MoveComponentRequest"] = _MOVECOMPONENTREQUEST
DESCRIPTOR.message_types_by_name["MoveComponentReply"] = _MOVECOMPONENTREPLY
DESCRIPTOR.message_types_by_name["CurrentPositionRequest"] = _CURRENTPOSITIONREQUEST
DESCRIPTOR.message_types_by_name["CurrentPositionReply"] = _CURRENTPOSITIONREPLY
DESCRIPTOR.message_types_by_name["Seat"] = _SEAT
DESCRIPTOR.message_types_by_name["SeatLocation"] = _SEATLOCATION
DESCRIPTOR.message_types_by_name["Position"] = _POSITION
DESCRIPTOR.enum_types_by_name["SeatComponent"] = _SEATCOMPONENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MoveRequest = _reflection.GeneratedProtocolMessageType(
    "MoveRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _MOVEREQUEST,
        "__module__": "seats_pb2"
        # @@protoc_insertion_point(class_scope:sdv.edge.comfort.seats.v1.MoveRequest)
    },
)
_sym_db.RegisterMessage(MoveRequest)

MoveReply = _reflection.GeneratedProtocolMessageType(
    "MoveReply",
    (_message.Message,),
    {
        "DESCRIPTOR": _MOVEREPLY,
        "__module__": "seats_pb2"
        # @@protoc_insertion_point(class_scope:sdv.edge.comfort.seats.v1.MoveReply)
    },
)
_sym_db.RegisterMessage(MoveReply)

MoveComponentRequest = _reflection.GeneratedProtocolMessageType(
    "MoveComponentRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _MOVECOMPONENTREQUEST,
        "__module__": "seats_pb2"
        # @@protoc_insertion_point(class_scope:sdv.edge.comfort.seats.v1.MoveComponentRequest)
    },
)
_sym_db.RegisterMessage(MoveComponentRequest)

MoveComponentReply = _reflection.GeneratedProtocolMessageType(
    "MoveComponentReply",
    (_message.Message,),
    {
        "DESCRIPTOR": _MOVECOMPONENTREPLY,
        "__module__": "seats_pb2"
        # @@protoc_insertion_point(class_scope:sdv.edge.comfort.seats.v1.MoveComponentReply)
    },
)
_sym_db.RegisterMessage(MoveComponentReply)

CurrentPositionRequest = _reflection.GeneratedProtocolMessageType(
    "CurrentPositionRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _CURRENTPOSITIONREQUEST,
        "__module__": "seats_pb2"
        # @@protoc_insertion_point(class_scope:sdv.edge.comfort.seats.v1.CurrentPositionRequest)
    },
)
_sym_db.RegisterMessage(CurrentPositionRequest)

CurrentPositionReply = _reflection.GeneratedProtocolMessageType(
    "CurrentPositionReply",
    (_message.Message,),
    {
        "DESCRIPTOR": _CURRENTPOSITIONREPLY,
        "__module__": "seats_pb2"
        # @@protoc_insertion_point(class_scope:sdv.edge.comfort.seats.v1.CurrentPositionReply)
    },
)
_sym_db.RegisterMessage(CurrentPositionReply)

Seat = _reflection.GeneratedProtocolMessageType(
    "Seat",
    (_message.Message,),
    {
        "DESCRIPTOR": _SEAT,
        "__module__": "seats_pb2"
        # @@protoc_insertion_point(class_scope:sdv.edge.comfort.seats.v1.Seat)
    },
)
_sym_db.RegisterMessage(Seat)

SeatLocation = _reflection.GeneratedProtocolMessageType(
    "SeatLocation",
    (_message.Message,),
    {
        "DESCRIPTOR": _SEATLOCATION,
        "__module__": "seats_pb2"
        # @@protoc_insertion_point(class_scope:sdv.edge.comfort.seats.v1.SeatLocation)
    },
)
_sym_db.RegisterMessage(SeatLocation)

Position = _reflection.GeneratedProtocolMessageType(
    "Position",
    (_message.Message,),
    {
        "DESCRIPTOR": _POSITION,
        "__module__": "seats_pb2"
        # @@protoc_insertion_point(class_scope:sdv.edge.comfort.seats.v1.Position)
    },
)
_sym_db.RegisterMessage(Position)


_SEATS = _descriptor.ServiceDescriptor(
    name="Seats",
    full_name="sdv.edge.comfort.seats.v1.Seats",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=785,
    serialized_end=1110,
    methods=[
        _descriptor.MethodDescriptor(
            name="Move",
            full_name="sdv.edge.comfort.seats.v1.Seats.Move",
            index=0,
            containing_service=None,
            input_type=_MOVEREQUEST,
            output_type=_MOVEREPLY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="MoveComponent",
            full_name="sdv.edge.comfort.seats.v1.Seats.MoveComponent",
            index=1,
            containing_service=None,
            input_type=_MOVECOMPONENTREQUEST,
            output_type=_MOVECOMPONENTREPLY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="CurrentPosition",
            full_name="sdv.edge.comfort.seats.v1.Seats.CurrentPosition",
            index=2,
            containing_service=None,
            input_type=_CURRENTPOSITIONREQUEST,
            output_type=_CURRENTPOSITIONREPLY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_SEATS)

DESCRIPTOR.services_by_name["Seats"] = _SEATS

# @@protoc_insertion_point(module_scope)
